;METADATA=(Diff=true, UseCommands=true)
[/Script/GameplayTags.GameplayTagsSettings]
ImportTagsFromConfig=True
WarnOnInvalidTags=True
ClearInvalidTags=False
AllowEditorTagUnloading=True
AllowGameTagUnloading=False
FastReplication=False
bDynamicReplication=False
InvalidTagCharacters="\"\',"
NumBitsForContainerSize=6
NetIndexFirstBitSegment=16
+GameplayTagList=(Tag="Ability.Blackhole.Cooldown",DevComment="")
+GameplayTagList=(Tag="Ability.Combo.Change.Combo02",DevComment="")
+GameplayTagList=(Tag="Ability.Dash.Cooldown",DevComment="")
+GameplayTagList=(Tag="Ability.GroundBlast.Cooldown",DevComment="")
+GameplayTagList=(Tag="Ability.Tornado.Cooldown",DevComment="")
+GameplayTagList=(Tag="GameplayCue.Blackhole.Blow",DevComment="")
+GameplayTagList=(Tag="GameplayCue.CameraShake",DevComment="")
+GameplayTagList=(Tag="GameplayCue.GroundBlast",DevComment="")
+GameplayTagList=(Tag="GameplayCue.Hit.Crunch.Dash",DevComment="")
+GameplayTagList=(Tag="GameplayCue.Hit.Crunch.Punch",DevComment="")
+GameplayTagList=(Tag="GameplayCue.Hit.Minion",DevComment="")
+GameplayTagList=(Tag="GameplayCue.Hit.Phase.Projectile",DevComment="")
+GameplayTagList=(Tag="GameplayCue.Hit.Reaction",DevComment="")

